from codegen.codegen import generate

config = {
    "project_name": "autointerface",
    "models": [{
        "name": "projects",
        "requires": [],
        "rules": [{
            "name": "name",
            "description": "项目名称",
            "type": "string",
            "null": False,
            "unique": True,
            "index": True
        }, {
            "name": "state",
            "description": "状态，1在线、2下线",
            "default": 1,
            "type": "integer",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "description",
            "description": "描述信息",
            "default": "",
            "type": "text",
            "null": False,
            "unique": False,
            "index": False
        }]
    }, {
        "name": "models",
        "requires": ["projects"],
        "rules": [{
            "name": "name",
            "description": "模型英文名称",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "name_cn",
            "description": "模型中文名称",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "description",
            "description": "描述信息",
            "default": "",
            "type": "text",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "project",
            "description": "项目外键",
            "null": False,
            "type": "foreign",
            "model": "projects",
            "on_delete": "CASCADE"
        }]
    }, {
        "name": "fields",
        "requires": ["models"],
        "rules": [{
            "name": "name",
            "description": "英文名称",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "description",
            "description": "描述信息",
            "default": "",
            "type": "text",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "default",
            "description": "默认值",
            "type": "json",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "type",
            "description": "类型",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "null",
            "description": "可否为空",
            "default": True,
            "type": "bool",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "unique",
            "description": "是否唯一",
            "default": False,
            "type": "bool",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "index",
            "description": "可否索引",
            "default": False,
            "type": "bool",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "foreign",
            "description": "外键专用，表示是谁的外键",
            "type": "integer",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "on_delete",
            "description": "外键专用，表示删除时的行为。CASCADE表示递归删除，参考peewee文档",
            "type": "string",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "model",
            "description": "模型外键",
            "null": False,
            "type": "foreign",
            "model": "models",
            "on_delete": "CASCADE",
        }]
    }, {
        "name": "interfaces",
        "requires": ["projects"],
        "rules": [{
            "name": "name",
            "description": "接口英文名称",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "name_cn",
            "description": "接口中文名称",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "method",
            "description": "GET、GETS、POST、PUT、DELETE",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "description",
            "description": "描述信息",
            "default": "",
            "type": "text",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "project",
            "description": "项目外键",
            "null": False,
            "type": "foreign",
            "model": "projects",
            "on_delete": "CASCADE"
        }]
    }, {
        "name": "params",
        "requires": ["interfaces"],
        "rules": [{
            "name": "name",
            "description": "参数名称",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "description",
            "description": "参数描述信息",
            "default": "",
            "type": "text",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "need",
            "description": "是否必填",
            "default": False,
            "type": "bool",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "default",
            "description": "默认值",
            "type": "json",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "min",
            "description": "最小值",
            "type": "integer",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "max",
            "description": "最大值",
            "type": "integer",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "choices",
            "description": "可选值",
            "type": "json",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "vtype",
            "description": "参数类型",
            "type": "string",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "function",
            "description": "参数用途，filter、sort、page",
            "type": "string",
            "null": False,
            "unique": False,
            "index": False
        }, {
            "name": "filter_op",
            "description": "过滤专用，表示过滤操作符",
            "type": "string",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "filter_condition",
            "description": "过滤专用，表示过滤条件",
            "type": "string",
            "null": True,
            "unique": False,
            "index": False
        }, {
            "name": "interface",
            "description": "接口外键",
            "null": False,
            "type": "foreign",
            "model": "interfaces",
            "on_delete": "CASCADE"
        }]
    }],
    "interfaces": [{
        "name": "projects",
        "name_cn": "项目",
        "post": {
            "params": [{
                "name": "name",
                "description": "项目名称",
                "need": True,
                "vtype": "string"
            }, {
                "name": "state",
                "description": "项目状态",
                "default": 1,
                "need": False,
                "vtype": "integer"
            }, {
                "name": "description",
                "description": "项目描述",
                "default": "",
                "need": False,
                "vtype": "string"
            }]
        }
    }, {
        "name": "models",
        "name_cn": "模型",
        "post": {
            "params": [{
                "name": "name",
                "description": "模型英文名称",
                "need": True,
                "vtype": "string"
            }, {
                "name": "name_cn",
                "description": "模型中文名称",
                "need": True,
                "vtype": "string"
            }, {
                "name": "description",
                "description": "模型描述",
                "need": False,
                "default": "",
                "vtype": "string"
            }, {
                "name": "project_id",
                "description": "项目ID",
                "need": True,
                "vtype": "integer"
            }]
        }
    }, {
        "name": "fields",
        "name_cn": "模型字段",
        "post": {
            "params": [{
                "name": "name",
                "need": True,
                "vtype": "string",
                "description": "",
            }, {
                "name": "description",
                "need": False,
                "default": "",
                "vtype": "string",
                "description": "",
            }, {
                "name": "default",
                "need": False,
                "description": "",
            }, {
                "name": "type",
                "need": True,
                "vtype": "string",
                "description": "",
            }, {
                "name": "null",
                "need": True,
                "vtype": "bool",
                "description": "",
            }, {
                "name": "unique",
                "need": True,
                "vtype": "bool",
                "description": "",
            }, {
                "name": "index",
                "need": True,
                "vtype": "bool",
                "description": "",
            }, {
                "name": "foreign",
                "need": False,
                "vtype": "integer",
                "description": "",
            }, {
                "name": "on_delete",
                "need": False,
                "vtype": "string",
                "description": "",
            }, {
                "name": "model_id",
                "need": True,
                "vtype": "integer",
                "description": "",
            }]
        }
    }, {
        "name": "interfaces",
        "name_cn": "接口",
        "requires": ["projects"],
        "post": {
            "params": [{
                "name": "name",
                "description": "接口英文名称",
                "vtype": "string",
                "need": True,
            }, {
                "name": "name_cn",
                "description": "接口中文名称",
                "vtype": "string",
                "need": True,
            }, {
                "name": "method",
                "description": "GET、GETS、POST、PUT、DELETE",
                "choices": ["GET", "GETS", "POST", "PUT", "DELETE"],
                "vtype": "string",
                "need": True,
            }, {
                "name": "description",
                "description": "描述信息",
                "default": "",
                "vtype": "string",
                "need": False,
            }, {
                "name": "project_id",
                "description": "项目外键",
                "vtype": "integer",
                "need": True,
            }]
        }
    }, {
        "name": "params",
        "name_cn": "接口参数",
        "requires": ["interfaces"],
        "post": {
            "params": [{
                "name": "name",
                "description": "参数名称",
                "vtype": "string",
                "need": True,
            }, {
                "name": "description",
                "description": "参数描述信息",
                "vtype": "string",
                "need": False,
            }, {
                "name": "need",
                "description": "是否必填",
                "vtype": "bool",
                "need": True,
            }, {
                "name": "default",
                "description": "默认值",
                "need": False,
            }, {
                "name": "min",
                "description": "最小值",
                "vtype": "integer",
                "need": False,
            }, {
                "name": "max",
                "description": "最大值",
                "vtype": "integer",
                "need": False,
            }, {
                "name": "vtype",
                "description": "参数类型",
                "vtype": "string",
                "need": False,
            }, {
                "name": "choices",
                "description": "可选值",
                "vtype": "list",
                "need": False,
            }, {
                "name": "function",
                "description": "参数用途，filter、sort、page",
                "vtype": "string",
                "default": "normal",
                "choices": ["normal", "filter", "sort", "page"]
            }, {
                "name": "filter_op",
                "description": "过滤专用，表示过滤操作符",
                "vtype": "string",
                "need": False,
            }, {
                "name": "filter_condition",
                "description": "过滤专用，表示过滤条件",
                "vtype": "string",
                "need": False,
            }, {
                "name": "interface_id",
                "description": "接口外键",
                "vtype": "integer",
                "need": True,
            }]
        }
    }]
}

generate(config)
